version: 2.1

orbs:
  haskell: haskell-works/haskell-build@4.0.2
  github: haskell-works/github-release@1.3.0
  hackage: haskell-works/hackage@1.1.0

executors:
  darwin:
    macos:
      xcode: 10.0

workflows:
  multiple-ghc-build:
    jobs:

      - haskell/build-with-binary-cache:
          name: GHC 8.6.5
          executor: haskell/ghc-8_6_5
          context: haskell-ci
          write-result-workspace: true
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct

      - haskell/build-with-cci-cache:
          name: Darwin
          executor: darwin
          run-tests: true
          fail-incoherent-builds: false
          write-result-workspace: true
          after-checkout:
          - restore_cache:
              keys:
                - nix
          - run:
              name: Install Nix
              command: curl https://nixos.org/nix/install | sh

          - run:
              name: Install dependencies
              command: nix-env -i jq

          - save_cache:
              key: nix
              paths:
                - /nix
                - ~/.nix-channels
                - ~/.nix-defexpr
                - ~/.nix-profile

          - restore_cache:
              keys:
                ghc-cache

          - run:
              name: Install GHC and Cabal
              command: |
                sh ./.circleci/ghcup.sh
                source ~/.bash_profile
                ghcup install 8.6.5
                # ghcup install-cabal 3.0.0.0
          - save_cache:
              key: ghc-cache
              paths: [~/.ghcup]


