version: 2.0
jobs:
  linux:
    working_directory: ~/build
    docker:
      - image: quay.io/haskell_works/stack-build-python

    steps:
      - checkout
      - run: git fetch --unshallow || true
      - run: grep '^resolver:' stack.yaml > resolver.txt

      - run:
          name: Copying scripts
          command: |
            mkdir -p ~/.local/bin
            cp ./scripts/* ~/.local/bin

      - restore_cache:
          keys:
            - dot-stack-{{ checksum "stack.yaml" }}-{{ checksum "avro-piper.cabal" }}
            - dot-stack-{{ checksum "stack.yaml" }}
            - dot-stack-{{ checksum "resolver.txt" }}
            - dot-stack-resolver-{{ checksum "resolver.txt" }}
      - run: stack setup
      - save_cache:
          key: dot-stack-resolver-{{ checksum "resolver.txt" }}
          paths:
            - ~/.stack
      - save_cache:
          key: dot-stack-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack

      - restore_cache:
          key: stack-work-{{ checksum "stack.yaml" }}
      - run: stack build --test --no-run-tests --dependencies-only
      - save_cache:
          key: dot-stack-{{ checksum "resolver.txt" }}
          paths:
            - ~/.stack

      - run: stack build --test --no-run-tests
      - save_cache:
          key: dot-stack-{{ checksum "stack.yaml" }}-{{ checksum "avro-piper.cabal" }}
          paths:
            - ~/.stack
      - save_cache:
          key: stack-work-{{ checksum "stack.yaml" }}
          paths: ~/build/.stack-work

      - run:
          name: Running unit tests
          command: stack test

      - deploy:
          command: |
            if [ "$CIRCLE_PROJECT_USERNAME" == "haskell-works" ]; then
              if [[ "$CIRCLE_BRANCH" == "master" ]]; then
                release
              fi
            fi

workflows:
  version: 2
  build-test-lint:
    jobs:
      - linux
