#!/usr/bin/env bash

if [ "$_system_type" == "Darwin" ]; then
  sed () {
    gsed "$@"
  }
fi

if [ "$HACKAGE_USER" == "" ] || [ "$HACKAGE_PASS" == "" ]; then
  echo "Must supply credentials"
  exit 1
fi

_version=$(cat *.cabal | grep -e "^version" | tr -s " " | cut -d' ' -f2)

if [ "v$_version" != "$CIRCLE_TAG" ]; then
  echo "Tag mismatch: "v$_version != $CIRCLE_TAG""
  exit 1
fi

if [ "$ALLOW_UPLOAD" != "" ]; then
  stack upload .
fi
